local nvchad_settings = require "nvchad.configs.treesitter"
local own_settings = {
  ensure_installed = {
    "bash",
    "bibtex",
    "c",
    "cmake",
    "comment",
    "cpp",
    "cuda",
    "diff",
    "gitignore",
    "glsl",
    "hlsl",
    "java",
    "json",
    -- "lua",
    "make",
    "markdown",
    "matlab",
    "meson",
    "ninja",
    -- "perl",
    "python",
    "rust",
    "vim",
    "yaml",
    -- "query",
    -- "latex",
  },
  -- ignore_install = { "fortran", "latex" },
  -- sync_install = true,
  -- auto_install = true,
  -- highlight = {
  --   enable = true,
  --   additional_vim_regex_highlighting = false,
  --   disable = { "fortran", "latex" },
  -- },
}
return vim.tbl_deep_extend("force", nvchad_settings, own_settings)
